In [54]:
import numpy as np
import pandas as pd
from sklearn import tree

In [61]:
restaurantDataset = pd.read_csv('data_restaurant2.csv',delimiter=',',header=0)

In [ ]:
restaurantDataset.head()

In [ ]:
restaurantDataset["Restaurant"] = pd.factorize(restaurantDataset.Restaurant)[0]

In [ ]:
restaurantDataset.head()

In [65]:
restaurantDataset = restaurantDataset.drop(labels="Rank",axis=1)

In [ ]:
print(restaurantDataset)

In [ ]:
restaurantDataset = restaurantDataset.to_numpy()

In [ ]:
print(restaurantDataset)

In [115]:
dataTraining = np.concatenate((restaurantDataset[0:5, :], restaurantDataset[10:15, :]),axis=0)
dataTesting = np.concatenate((restaurantDataset[40:45, :], restaurantDataset[20:25, :]),axis=0)

In [ ]:
print(dataTesting)
len(dataTesting)

In [116]:
print(dataTraining)
len(dataTraining)

[[2.400e+01 1.305e+00 2.600e+01 1.167e+00 1.150e+03 0.000e+00]
 [4.400e+01 1.219e+00 1.050e+02 9.440e-01 5.600e+02 1.000e+00]
 [2.100e+01 8.100e-01 2.100e+01 9.090e-01 1.370e+03 2.000e+00]
 [2.500e+01 7.970e-01 4.600e+01 5.860e-01 6.850e+02 3.000e+00]
 [4.900e+01 7.710e-01 5.000e+01 5.630e-01 1.210e+03 4.000e+00]
 [3.000e+01 3.540e-01 4.100e+01 3.670e-01 8.600e+02 1.000e+01]
 [3.900e+01 3.450e-01 5.000e+01 4.290e-01 1.200e+03 1.100e+01]
 [4.100e+01 3.410e-01 6.300e+01 6.580e-01 8.900e+02 1.200e+01]
 [4.800e+01 3.300e-01 4.800e+01 3.710e-01 1.175e+03 1.300e+01]
 [2.100e+01 3.250e-01 1.200e+01 2.000e-01 1.930e+03 1.400e+01]]


10

In [131]:
inputTraining = dataTraining[:,0:4]
inputTesting = dataTesting[:,0:4]
labelTraining = dataTraining[:,4]
labelTesting = dataTesting[:,4]

In [117]:
model = tree.DecisionTreeClassifier()

In [104]:
model = model.fit(inputTraining, labelTraining)

In [105]:
hasilPrediksi = model.predict(inputTesting)

In [132]:
print("Label sebenarnya ",labelTesting)
print("Hasil prediksi ",hasilPrediksi)

Label sebenarnya  [3500.  535. 2700. 1620. 1260. 4300.  530. 2230.  760. 2800.]
Hasil prediksi  [4260. 1050. 4260. 1240. 1050. 1050. 1050. 1050. 1050. 1050. 1510. 1510.
 1510. 1510. 1510. 1510. 1510. 1510. 1510. 1510.]


In [119]:
prediksiBenar = (hasilPrediksi == labelTesting).sum()
prediksiSalah = (hasilPrediksi != labelTesting).sum()

In [136]:
print("Prediksi benar: ", prediksiBenar, " data")
print("Prediksi salah: ", prediksiSalah, " data")
print("Akurasi: ",prediksiBenar/(prediksiBenar+prediksiSalah)*100,"%")

Prediksi benar:  0  data
Prediksi salah:  20  data
Akurasi:  0.0 %
