In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
dataset = pd.read_csv('Data.csv')
x = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

In [3]:
print(x)

[['Bata' 36.0 72000.0]
 ['Adidas' 27.0 48000.0]
 ['Briefstock' 30.0 54000.0]
 ['Adidas' 28.0 61000.0]
 ['Briefstock' 26.0 nan]
 ['Bata' 35.0 58000.0]
 ['Adidas' nan 52000.0]
 ['Bata' 40.0 79000.0]
 ['Briefstock' 39.0 83000.0]
 ['Bata' 38.0 67000.0]]


In [4]:
print(y)

['No' 'Yes' 'No' 'No' 'Yes' 'Yes' 'No' 'Yes' 'No' 'Yes']


In [5]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
imputer.fit(x[:, 1:3])
x[:, 1:3] = imputer.transform(x[:, 1:3])

In [6]:
print(x)

[['Bata' 36.0 72000.0]
 ['Adidas' 27.0 48000.0]
 ['Briefstock' 30.0 54000.0]
 ['Adidas' 28.0 61000.0]
 ['Briefstock' 26.0 63777.77777777778]
 ['Bata' 35.0 58000.0]
 ['Adidas' 33.22222222222222 52000.0]
 ['Bata' 40.0 79000.0]
 ['Briefstock' 39.0 83000.0]
 ['Bata' 38.0 67000.0]]


In [7]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [0])], remainder='passthrough')
x = np.array(ct.fit_transform(x))

In [8]:
print(x)

[[0.0 1.0 0.0 36.0 72000.0]
 [1.0 0.0 0.0 27.0 48000.0]
 [0.0 0.0 1.0 30.0 54000.0]
 [1.0 0.0 0.0 28.0 61000.0]
 [0.0 0.0 1.0 26.0 63777.77777777778]
 [0.0 1.0 0.0 35.0 58000.0]
 [1.0 0.0 0.0 33.22222222222222 52000.0]
 [0.0 1.0 0.0 40.0 79000.0]
 [0.0 0.0 1.0 39.0 83000.0]
 [0.0 1.0 0.0 38.0 67000.0]]


In [9]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)

In [10]:
print(y)

[0 1 0 0 1 1 0 1 0 1]


In [11]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x,y, test_size=0.2, random_state=1)

In [12]:
print(x_train)

[[1.0 0.0 0.0 33.22222222222222 52000.0]
 [0.0 0.0 1.0 26.0 63777.77777777778]
 [0.0 1.0 0.0 36.0 72000.0]
 [1.0 0.0 0.0 28.0 61000.0]
 [1.0 0.0 0.0 27.0 48000.0]
 [0.0 1.0 0.0 40.0 79000.0]
 [0.0 0.0 1.0 39.0 83000.0]
 [0.0 1.0 0.0 35.0 58000.0]]
